Tic tac toe
wolox-training/tr-react-native pull request #10
Opened 2018-08-23 20:46 UTC by tomiir

## Summary
Developed Tic-Tac-Toe application folowing instructions from https://reactjs.org/tutorial/tutorial.html#getting-started.

Developed 4 React Components: 
- Square: Container for crosses and circles.
- Board: Collection of Squares representing a game board.
- Game: Logical container for the game. Manages the logic behind the application.
- App: Main container for the app.

## GIF
![tateti](https://user-images.githubusercontent.com/12738697/44551034-54d4c600-a6fc-11e8-978d-08e8cda7dd31.gif)

## Trello Card
https://trello.com/c/dvAzCk6b

2018-08-27 13:18 UTC, mvbattan requested changes

2018-08-27 13:18 UTC, mvbattan commented on tic-tac-toe/public/index.html
> +    <title>React App</title>
Later, if you need to customize project titles on projects, we should modify this file

2018-08-27 13:18 UTC, mvbattan commented on tic-tac-toe/src/app/components/App/index.js
> +class App extends React.Component {
Use `extends Component` by importing
```
import React, { Component } from 'react';
```

2018-08-27 13:18 UTC, mvbattan commented on tic-tac-toe/src/app/components/App/index.scss
> +body {
🤔 Is this file being used ? In that case, this should be named `styles.scss`

2018-08-27 13:18 UTC, mvbattan commented on tic-tac-toe/src/app/components/App/styles.scss
> +}
Is this file being used ?

2018-08-27 13:18 UTC, mvbattan commented on tic-tac-toe/src/app/components/Board/index.js
> +  }
As a convention, we write all non-lifecycle hooks with `arrow` functions 😊

2018-08-27 13:18 UTC, mvbattan commented on tic-tac-toe/src/app/components/Board/index.js
> +      <div>
I'd use a `Fragment` here. What do you think ?

2018-08-27 13:18 UTC, mvbattan commented on tic-tac-toe/src/app/components/Game/index.js
> +class Game extends React.Component {
Use `Component`

2018-08-27 13:18 UTC, mvbattan commented on tic-tac-toe/src/app/components/Game/index.js
> +function calculateWinner(squares) {
I'd extract this function into a `utils` file

2018-08-27 13:18 UTC, mvbattan commented on tic-tac-toe/src/app/components/Game/index.js
> +  handleClick(i) {
I'd write this as `arrow`

2018-08-27 13:18 UTC, mvbattan commented on tic-tac-toe/src/app/components/Game/index.js
> +  jumpTo(step) {
Same here

2018-08-27 13:18 UTC, mvbattan commented on tic-tac-toe/src/app/components/Game/index.js
> +    this.setState({
Fun fact: Did you know that `setState` is asynchronous ? 🤓

2018-08-27 13:18 UTC, mvbattan commented on tic-tac-toe/src/app/components/Game/index.js
> +          squares: squares
We can shorten this by just writing `{ squares }`

2018-08-27 13:18 UTC, mvbattan commented on tic-tac-toe/src/app/components/Game/index.js
> +    squares[i] = this.state.xIsNext ? 'X' : 'O';
I'd extract `X`, `O` literals as constants

2018-08-27 13:18 UTC, mvbattan commented on tic-tac-toe/src/app/components/Game/index.js
> +      const desc = move ? 'Go to move #' + move : 'Go to game start';
I'd extract these string literals into a `strings.js` file under this folder. What do you think ?

2018-08-27 13:18 UTC, mvbattan commented on tic-tac-toe/src/app/components/Game/index.js
> +      const desc = move ? 'Go to move #' + move : 'Go to game start';
I'd avoid string concatenation in favor of string interpolation:
```
'Go to move #' + move
```
is equivalent to
```
`Go to move #${move}`
```

2018-08-27 13:18 UTC, mvbattan commented on tic-tac-toe/src/app/components/Game/index.js
> +          <Board squares={current.squares} onClick={i => this.handleClick(i)} />
We should pass `this.handleClick` reference directly here. Does this work ? Why ?

2018-08-27 13:18 UTC, mvbattan commented on tic-tac-toe/src/app/components/Game/index.js
> +    const squares = current.squares.slice();
Does 
`const squares = [...current.squares];`
work ? Why ?

2018-08-27 13:18 UTC, mvbattan commented on tic-tac-toe/src/app/components/Square/index.js
> +      }}
I'd pass `onClick` reference directly

2018-08-27 13:18 UTC, mvbattan commented on tic-tac-toe/src/app/components/Square/index.js
> +function Square(props) {
I'd `destructure` these props at this level:
```
function Square({ onClick, value }) {
```

2018-08-27 13:18 UTC, mvbattan commented on tic-tac-toe/src/app/components/Game/index.js
> +    const history = this.state.history;
This render is doing many things. If possible, I'd modularize this one in order to make this `render` short as possible.

2018-08-27 13:41 UTC, tomiir commented on tic-tac-toe/src/app/components/App/styles.scss
> +}
This file contains some formatting used on the app. It can be removed but the text styles would change.

2018-08-27 15:15 UTC, mvbattan commented on tic-tac-toe/src/utils/gameUtils.js
> +  return move ? `Go to move #${move}` : 'Go to game start';
Remember to extract strings 😇

2018-08-27 15:15 UTC, mvbattan commented on tic-tac-toe/src/utils/gameUtils.js
> +const O = 'O';
These constants are already defined in another place. Would you like to put them in a common file ?
Moreover, IMHO names of constants shouldn't depend of the content itself - otherwise, names and contents will be coupled. I'd rename these to `FIRST_PLAYER` or something alike, so we can customize the avatars later. What do you think ?

2018-08-27 16:40 UTC, mvbattan commented on tic-tac-toe/src/app/components/App/styles.scss
> +}
Let's remove those not being used, like `.app-logo` animation by example

2018-08-27 16:40 UTC, mvbattan commented on tic-tac-toe/src/utils/strings.js
> +export const strings = { PLAYER_ONE, PLAYER_TWO, MOVE_MSG, MOVE_START, NEXT_PLAYER, WINNER };
The only drawback for this one is that, if we need to add a string, we need to modify both content and this object. A cleaner approach would be:
```
export default {
  PLAYER_ONE: 'X',
  PLAYER_TWO: 'O',
  ...
}
```
And so on

2018-08-29 12:39 UTC, mvbattan approved these changes

2018-08-29 12:45 UTC, merged