Front end tools
wolox-training/tr-react-native pull request #2
Opened 2018-08-08 16:56 UTC by tomiir

##Summary
Modified index.html and titles.scss to center text on title image.

##Screenshot
![title comparison](https://user-images.githubusercontent.com/12738697/43852113-d249dd1e-9b12-11e8-9cde-b0aab7e35b1a.png)

##Trello Card
https://trello.com/c/DMRDozUb

2018-08-08 18:27 UTC, HarryPerez requested changes

2018-08-08 18:27 UTC, HarryPerez commented on index.html
> +  <h1 class="title">
You will have a lot of titles in you app. I would write here something like this `main-title` or `tech-title`.

2018-08-08 18:27 UTC, HarryPerez commented on index.html
> +  <h1 class="title">
Also i would put this title inside a container.
For example:
<img width="453" alt="captura de pantalla 2018-08-08 a la s 15 16 03" src="https://user-images.githubusercontent.com/36163179/43856123-05204d1c-9b1e-11e8-9798-2c630ee46337.png">


The `body-container` should have styles like this:
```
.body-container {
  margin: 0 auto;
  max-width: 1280px;
  padding: 100px 40px;
  width: 100%;
}
```
* 1280px is a default screen width that we are used to use
* padding is used in order to separate the screen from the content

2018-08-08 18:27 UTC, HarryPerez commented on scss/application.scss
> +@import "titles";
Use simple quotes `@import 'titles';` here

2018-08-08 18:27 UTC, HarryPerez commented on scss/styles.scss
> +$blue: #00ADEE;
You should have another files separating vars:
* `sizes.scss`
```
$nav-height: 70px;
$nav-logo-height: 30px;
$title-decoration-height: 90px;
$title-decoration-width: 70px;
$tech-logo-size: 100px;
$text-big: 24px;
$text-small: 12px;
$text-medium: 16px;
```

* `colors.scss`
```
$blue: #00ADEE;
$green: #BED23C;
$grey: #C4C4C4;
```

`Take this as a good practice`

2018-08-08 18:27 UTC, HarryPerez commented on scss/titles.scss
> +  color: black;
this is not needed

2018-08-08 18:27 UTC, HarryPerez commented on scss/titles.scss
> +.title::before {
You should put `::before` inside `.title {` definition
```
.title {
...etc
&::before {
   ... etc
  }
}
```

2018-08-08 18:27 UTC, HarryPerez commented on scss/titles.scss
> +.title::before {
in `before`
try something like this:
```
 &::before {
    background: url('./assets/triangle.svg') no-repeat;
    content: '';
    width: xxx
    height: xxx
    position: absolute;
    top: -18px;
    left: -28px;
    z-index: -1;
  }
```

2018-08-08 18:52 UTC, tomiir commented on scss/titles.scss
> +.title::before {
Is is OK to use position:absolute? How does that work when what we are positioning is part of a component? Wouldn't it stay at a fixed position, independent from where the component is located?

2018-08-08 19:13 UTC, tomiir commented
## Summary
Added container to Title Component.
Added corresponding padding to match reference image.
Changed class name to be more specific.
Included ::before inside title class definition.
Divided styles scss into colors and sizes.

## Screenshot

## Trello Card 
https://trello.com/c/DMRDozUb

2018-08-08 19:21 UTC, HarryPerez requested changes

2018-08-08 19:21 UTC, HarryPerez commented on index.html
> +  <div class = "tech">
this is not inside the scope of this card

2018-08-08 19:21 UTC, HarryPerez commented on scss/application.scss
> +@import 'tech';
this is not inside the scope of this card

2018-08-08 19:21 UTC, HarryPerez commented on scss/application.scss
> +@import 'colors';
You can write `@import 'https://fonts.google.com/specimen/Roboto?selection.family=Roboto'; Here to import this font

2018-08-08 19:21 UTC, HarryPerez commented on scss/styles.scss
> -.title {
You can write here 
```
* {
    font-family: 'Roboto', sans-serif;
}
``` 
In order to use it in the whole app

2018-08-08 19:21 UTC, HarryPerez commented on scss/titles.scss
> +margin: 0 auto;
add tabulation here. Remember that we use identation. And the identation is one tab (Two empty spaces)
```
.body-container {
  margin: 0 auto;
  max-width: 1280px;
  padding: 100px 40px;
  width: 100%;
}
```

2018-08-08 20:36 UTC, HarryPerez requested changes

2018-08-08 20:36 UTC, HarryPerez commented on scss/sizes.scss
> +$title-font: "Roboto", sans-serif;
this is not needed, because you are using 
```
* {
    font-family: 'Roboto', sans-serif;
}
```

In another file

2018-08-08 20:36 UTC, HarryPerez commented on scss/application.scss
> +@import 'https://fonts.google.com/specimen/Roboto?selection.family=Roboto';
You have to import this font before using it. So you have to import it in a higher level.
I would put it after `@import 'equalizer';`
```
@import 'equalizer';
@import 'https://fonts.google.com/specimen/Roboto?selection.family=Roboto';
```

2018-08-08 20:36 UTC, HarryPerez commented on .gitignore
> +.scss-cache
you have to write `.sass-cache` not `.scss-cache`

2018-08-08 20:36 UTC, HarryPerez commented on scss/titles.scss
> +  color: black;
Use colors defined in the `colors.scss` file

2018-08-09 13:27 UTC, HarryPerez requested changes

2018-08-09 13:27 UTC, HarryPerez commented on .gitignore
> +.scss-cache
check this!

2018-08-09 16:45 UTC, HarryPerez approved these changes

2018-08-09 16:45 UTC, HarryPerez commented
Great Work!!!!!!

2018-08-09 16:46 UTC, merged